debug = true
persist_dir = "/persist/"

[mfi]
selftest = false

[mfi.i2c]
bus_offset = 3
dev_addr = 0x11
timeout_ms = 1000

[mfi.server]
enabled = true
bind = "0.0.0.0:9000"

[bluetooth]
enabled = false
device = "hci0"
name = "CatPlay-V851S"

[wifi]
enabled = false
device = "wlan0"

[wifi_network]
ssid = "CatPlay-V851S"
password = "catplay123"
wpa = true
channel = 36

[gadget]
enabled = false
pinned = false
udc_car = "musb-hdrc.2.auto"
